/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as pubPubPubIdRouteImport } from './routes/(pub)/pub.$pubId'
import { Route as onboardingOnboardingPubRouteImport } from './routes/(onboarding)/onboarding.pub'
import { Route as onboardingOnboardingFanRouteImport } from './routes/(onboarding)/onboarding.fan'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const pubPubPubIdRoute = pubPubPubIdRouteImport.update({
  id: '/(pub)/pub/$pubId',
  path: '/pub/$pubId',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingOnboardingPubRoute = onboardingOnboardingPubRouteImport.update({
  id: '/(onboarding)/onboarding/pub',
  path: '/onboarding/pub',
  getParentRoute: () => rootRouteImport,
} as any)
const onboardingOnboardingFanRoute = onboardingOnboardingFanRouteImport.update({
  id: '/(onboarding)/onboarding/fan',
  path: '/onboarding/fan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/onboarding/fan': typeof onboardingOnboardingFanRoute
  '/onboarding/pub': typeof onboardingOnboardingPubRoute
  '/pub/$pubId': typeof pubPubPubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/onboarding/fan': typeof onboardingOnboardingFanRoute
  '/onboarding/pub': typeof onboardingOnboardingPubRoute
  '/pub/$pubId': typeof pubPubPubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/plan': typeof PlanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/(onboarding)/onboarding/fan': typeof onboardingOnboardingFanRoute
  '/(onboarding)/onboarding/pub': typeof onboardingOnboardingPubRoute
  '/(pub)/pub/$pubId': typeof pubPubPubIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/plan'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/waitlist'
    | '/onboarding/fan'
    | '/onboarding/pub'
    | '/pub/$pubId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/plan'
    | '/sitemap.xml'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/admin/waitlist'
    | '/onboarding/fan'
    | '/onboarding/pub'
    | '/pub/$pubId'
    | '/api/auth/$'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/plan'
    | '/sitemap.xml'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(dashboard)/dashboard'
    | '/admin/waitlist'
    | '/(onboarding)/onboarding/fan'
    | '/(onboarding)/onboarding/pub'
    | '/(pub)/pub/$pubId'
    | '/api/auth/$'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PlanRoute: typeof PlanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  onboardingOnboardingFanRoute: typeof onboardingOnboardingFanRoute
  onboardingOnboardingPubRoute: typeof onboardingOnboardingPubRoute
  pubPubPubIdRoute: typeof pubPubPubIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pub)/pub/$pubId': {
      id: '/(pub)/pub/$pubId'
      path: '/pub/$pubId'
      fullPath: '/pub/$pubId'
      preLoaderRoute: typeof pubPubPubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/onboarding/pub': {
      id: '/(onboarding)/onboarding/pub'
      path: '/onboarding/pub'
      fullPath: '/onboarding/pub'
      preLoaderRoute: typeof onboardingOnboardingPubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(onboarding)/onboarding/fan': {
      id: '/(onboarding)/onboarding/fan'
      path: '/onboarding/fan'
      fullPath: '/onboarding/fan'
      preLoaderRoute: typeof onboardingOnboardingFanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminWaitlistRoute: typeof AdminWaitlistRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminWaitlistRoute: AdminWaitlistRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PlanRoute: PlanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  onboardingOnboardingFanRoute: onboardingOnboardingFanRoute,
  onboardingOnboardingPubRoute: onboardingOnboardingPubRoute,
  pubPubPubIdRoute: pubPubPubIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
